### ISSUE TITLE
Handle full blocks

### ISSUE THREAD

**Issue by edd** [vegaprotocol/wendy#18]
Wendy needs to handle full blocks. This is covered in the spec.

Two thing to consider: 
- Full blocks from a single bucket
- Full blocks, multiple buckets

**Comment by gchaincl** [comment]
This has been addressed and parameterized here: https://pkg.go.dev/github.com/vegaprotocol/wendy@v0.3.0#NewBlockOptions.
The option allows a caller to specify a maximum Tx set size (other block metadata is not considered here, since Wendy is blockchain independent, and the only parameter we can control is the Tx size).

@Vegaklaus could you confirm if this solves your concern about full blocks?

**Comment by Vegaklaus** [comment]
I’ll have a look; meanwhile, I thought a bit more about the signatures, and the best would be to not only sign a vote I send, but also add a hashchain of all previous votes ;I’ll seek that tomorrow if possible).

**Comment by gchaincl** [comment]
Closed by https://github.com/vegaprotocol/wendy/commit/692466a
